# Generated by Django 5.1.2 on 2024-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='username',
            field=models.CharField(default='default_password', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
