# Generated by Django 5.1.2 on 2024-12-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_seller_user_seller_password_seller_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
