# Generated by Django 5.1.2 on 2025-01-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
