# Generated by Django 5.1.2 on 2025-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_address_line1_address_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
