# Generated by Django 5.1.2 on 2024-12-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='photo',
            new_name='image',
        ),
    ]
