# Generated by Django 5.1.2 on 2025-01-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
