# Generated by Django 5.1.2 on 2025-01-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
        migrations.AddField(
            model_name='product',
            name='gender_age_group',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('B', 'Boy'), ('G', 'Girl'), ('A', 'All')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('percentage', '%'), ('fixed', '₹')], default='percentage', max_length=10),
        ),
    ]
