# Generated by Django 5.1.2 on 2025-02-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
