# Generated by Django 5.1.2 on 2024-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='last_resend_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
