# Generated by Django 5.1.2 on 2025-01-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
    ]
